# Generated by Django 5.1.6 on 2025-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('belt', models.CharField(choices=[('W', 'White'), ('B', 'Blue'), ('P', 'Purple'), ('Br', 'Brown'), ('Bl', 'Black')], default='B', max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
