# Generated by Django 5.1.6 on 2025-02-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='belt',
            field=models.CharField(choices=[('W', 'White'), ('B', 'Blue'), ('P', 'Purple'), ('Br', 'Brown'), ('Bl', 'Black')], default='W', max_length=2),
        ),
        migrations.CreateModel(
            name='CompletedClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('current_belt', models.CharField(choices=[('W', 'White'), ('B', 'Blue'), ('P', 'Purple'), ('Br', 'Brown'), ('Bl', 'Black')], default='W', max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.students')),
            ],
        ),
    ]
